library("readxl")
library(ggplot2)
library(reshape2)
library(fields)
library(randomforest)
library(data.table)


```{r Part 1 - 1}
nm <- list.files(path="training/")
labelz = read_excel("training/labels.xlsx")[1:24,]
for(i in 1:24){ #Train data - RAW
  a = paste0("training/",nm[i])
  assign(paste0("train",substring(nm[i], 12,15)),read.csv(a))
}

for(i in 1:24){ #Train data - Matrix
  a = paste0("training/",nm[i])
  assign(paste0("train",substring(nm[i], 12,15),"Mat"),data.matrix(read.csv(a)[133:2630,4:302]))
}

nm <- list.files(path="testing/")
for(i in 1:6){ #Test data - RAW
  a = paste0("testing/",nm[i])
  assign(paste0("test",substring(nm[i], 12,15)),data.matrix(read.csv(a)[133:2630,4:302]))
}
```

```{r Part 1 - 2}
Grad = colorRampPalette(c('grey',"blue","red","black"))
{
par(mfrow = c(2,1))
dataCit = paste0('train',substring(labelz[sample(which(labelz$candy == "citrus"), 1),1],12,15),'Mat')
par(mar = c(0,0,1,0))
image(get(dataCit), useRaster=TRUE, axes=FALSE, col = Grad(10), main = "Citrus candy")
image.plot(legend.only=TRUE, zlim=c(min(get(dataCit)),max(get(dataCit))),col = Grad(100))

dataHal = paste0('train',substring(labelz[sample(which(labelz$candy == "halls"), 1),1],12,15),'Mat')
par(mar = c(0,0,1,0))
image(get(dataHal), useRaster=TRUE, axes=FALSE, col = Grad(10), main = "Halls candy")
image.plot(legend.only=TRUE, zlim=c(min(get(dataHal)),max(get(dataHal))),col = Grad(100))
}
```

```{r Part 1 - 3}
##########Loading in the data##########
nm <- list.files(path="peaxData/training_peax/")
testData = data.frame()
for(i in 1:24){ #Train data - Peax
  a = paste0("peaxData/training_peax/",nm[i])
  assign(paste0("peax",substring(nm[i], 12,15)),cbind(paste0(substring(nm[i], 12,15)),fread(a)[,3:4]))
}
nm <- list.files(path="peaxData/testing_peax/")
for(i in 25:30){ #Test data - Peax
  a = paste0("peaxData/testing_peax/",nm[i])
  assign(paste0("peax",substring(nm[i], 19,22)),cbind(paste0(substring(nm[i], 19,22)),fread(a)[,3:4]))
}
#######################################
#Putting all data into two groups, test and train
a = substring(nm, 12,15)[1:24]
dataTrain = do.call(rbind.data.frame, mget(paste0('peaxTr', a)))
a = substring(nm, 19,22)[25:30]
dataTest = do.call(rbind.data.frame, mget(paste0('peaxTe', a)))

#Combining the datasets and normalizing them
totDat = rbind(dataTrain,dataTest)
for(i in 1:length(totDat$t)){
  totDat$t[i] = totDat$t[i]/max(totDat$t)
  totDat$r[i] = totDat$r[i]/max(totDat$r)
}

```

```{r Part 1 - 4}
kNNdistplot(data.matrix(totDat[,2:3]), k=5) #finding out what epsilon to use for DBscan
db = dbscan(data.matrix(totDat[,2:3]),0.025) 
totDat$clusters = db$cluster #add dbscan clusters to dataset

#Making our boolean datamatrix
a = data.frame(matrix(0L,ncol=31,nrow=max(db$cluster)));colnames(a) = unique(totDat$V1)
for(i in 1:length(a)){
  inter = unique(totDat[which(totDat$V1 == colnames(a)[i]),]$clusters)
  a[,i] = as.numeric(as.numeric(rownames(a)) %in% inter)
}
```

```{r Part 1 - 5}
#Load the lables
labelz = read.xls("labels.xlsx")[1:24,]
```

```{r Part 1 - 6}
#Splitting it into test and train data and adding labels
dataTrain = data.frame(t(a[1:24]));dataTrain$labels = labelz$candy;dataTrain$labels = droplevels(dataTrain$labels)
dataTest = data.frame(t(a[24:29]))
```

```{r Part 2 - 7}
#See Part 1 - 6
```

```{r Part 2 - 8}
forFit = randomForest(labels ~ .,data = dataTrain, ntree=20);plot(fitFor);fitFor$confusion
```

```{r Part 2 - 9}
rf.crossValidation(fitFor,dataTrain,n=5, p=0.2)
```

```{r Part 2 - 10}
fitFor$confusion
```

```{r Part 2 - 11}
gini =  data.frame(fitFor$importance); gini$peak = rownames(gini)
gini = gini[order(gini$MeanDecreaseGini, decreasing = T),][1:5,]
```

```{r Part 2 - 12}
newTrain = dataTrain[,c(which(colnames(dataTrain) %in% gini$peak),27)] #Create new data matrix

#Single tree using giniData
giniTree = rpart(labels ~ ., data = newTrain, control = rpart.control(minsplit = 2))
prp(giniTree);predict(giniTree,dataTest)

#Random forest using giniData
giniFit = randomForest(labels ~ .,data = newTrain, ntree=25);plot(giniFit);giniFit$confusion
```

```{r Part 3 - 13}
#We use test data created earlier. See Part 1 - 6
```

```{r Part 3 - 14}
predict(giniFit,dataTest)
```

```{r Part 3 - 15}
#Prediction using inital random forest
forestPred = cbind("raw_file_name"=list.files(path="~testing/"),"class_label"=predict(forFit,dataTest))
forestPred[forestPred == 2] <- "halls"; forestPred[forestPred == 1] <- "citrus"
write.table(forestPred, file = "initalPred.csv",sep="\t",quote=F,row.names = F)

#Prediction using gini regulated random forest
giniPred = cbind("raw_file_name"=list.files(path="testing/"),"class_label"=predict(giniFit,dataTest))
giniPred[giniPred == 2] <- "halls"; giniPred[giniPred == 1] <- "citrus"
write.table(giniPred, file = "giniPred.csv",sep="\t",quote=F,row.names = F)
```

